# Generated by Django 3.1.3 on 2020-12-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201209_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='phone',
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(to='accounts.Tag'),
        ),
    ]
